import torch
import torch.nn as nn
import torch.nn.functional as F
from config import Config, TrypsinConfig

class MichaelisMentenLayer(nn.Module):
    """
    Non-trainable physics layer:
    maps predicted kcat / Km to reaction rate under given conditions.
    """
    def __init__(self, epsilon: float = Config.EPSILON):
        super().__init__()
        self.epsilon = epsilon

    def forward(self, kcat, km, enzyme_conc, substrate_conc):
        substrate_conc = torch.clamp(substrate_conc, min=self.epsilon)
        enzyme_conc = torch.clamp(enzyme_conc, min=self.epsilon)
        vmax = kcat * enzyme_conc
        return (vmax * substrate_conc) / (km + substrate_conc + self.epsilon)


class KineticsPredictor(nn.Module):
    """
    Main backbone for kinetic-parameter prediction:
    Input: [E_emb, S_emb]
    Output: kcat / Km

    When substrate and enzyme concentrations are provided, it also returns
    the corresponding rate prediction v0_pred, so one model supports both
    parameter supervision and experimental rate supervision.
    """
    def __init__(self,
                 enzyme_dim=Config.ENZYME_DIM,
                 substrate_dim=Config.SUBSTRATE_DIM,
                 hidden_dim=Config.HIDDEN_DIM,
                 dropout=Config.DROPOUT):
        super().__init__()

        self.enzyme_projector = nn.Sequential(
            nn.Linear(enzyme_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU()
        )
        self.substrate_projector = nn.Sequential(
            nn.Linear(substrate_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU()
        )
        fusion_dim = hidden_dim + hidden_dim
        self.trunk = nn.Sequential(
            nn.Linear(fusion_dim, 512),
            nn.BatchNorm1d(512),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(512, 256),
            nn.GELU(),
            nn.Dropout(dropout),
        )
        self.kcat_head = nn.Linear(256, 1)
        self.km_head = nn.Linear(256, 1)
        self.physics_layer = MichaelisMentenLayer()

    def encode(self, enzyme_embed, substrate_fp):
        """
        Encode enzyme/substrate inputs into a fused latent representation.

        This representation is used by both prediction heads and active-learning
        scoring (novelty / representativeness analysis).
        """
        e_feat = self.enzyme_projector(enzyme_embed)
        s_feat = self.substrate_projector(substrate_fp)
        x_fused = torch.cat([e_feat, s_feat], dim=1)
        return self.trunk(x_fused)

    def forward(self, enzyme_embed, substrate_fp, substrate_conc=None, enzyme_conc=None, return_hidden=False):
        hidden = self.encode(enzyme_embed, substrate_fp)

        log_kcat = self.kcat_head(hidden)
        log_km = self.km_head(hidden)
        kcat = torch.exp(log_kcat)
        km = torch.exp(log_km)

        outputs = {
            "log_kcat": log_kcat,
            "log_km": log_km,
            "kcat": kcat,
            "km": km,
        }

        if substrate_conc is not None and enzyme_conc is not None:
            outputs["v0_pred"] = self.physics_layer(kcat, km, enzyme_conc, substrate_conc)

        if return_hidden:
            outputs["hidden"] = hidden

        return outputs

    def generate_rate_curve(self, kcat, km, enzyme_conc, substrate_grid):
        return self.physics_layer(kcat, km, enzyme_conc, substrate_grid)


# =============================================================================
# Trypsin-Specific Closed-Loop Active Learning Architecture
# Step 1: Temperature-Conditioned PINN  (Hill Equation)
# Step 2: Deep Ensemble for Uncertainty Quantification
# =============================================================================

class HillLayer(nn.Module):
    """
    Non-trainable physics layer implementing the Hill equation.

    Generalises Michaelis-Menten (n=1) to support cooperative kinetics:

        v = V_max * [S]^n / (K_half^n + [S]^n)

    All parameters are generated by the upstream MLP; this layer only
    applies the thermodynamic constraint — no learnable weights.
    """
    def __init__(self, epsilon: float = TrypsinConfig.EPSILON):
        super().__init__()
        self.epsilon = epsilon

    def forward(self, V_max, K_half, n, substrate_conc):
        """
        Args:
            V_max         : (Batch, 1)  Maximum velocity          [µM/s]
            K_half        : (Batch, 1)  Half-saturation constant  [µM]
            n             : (Batch, 1)  Hill coefficient           [dimensionless, ≥ 0.5]
            substrate_conc: (Batch, 1)  [S]                       [µM]
        Returns:
            v             : (Batch, 1)  Reaction velocity          [µM/s]
        """
        S = torch.clamp(substrate_conc, min=self.epsilon)  # ensure [S] > 0
        S_n   = S.pow(n)
        K_n   = K_half.pow(n)
        v     = (V_max * S_n) / (K_n + S_n + self.epsilon)
        return v


class TrypsinKineticsNet(nn.Module):
    """
    Single ensemble member: Temperature-Conditioned PINN for Trypsin.

    Architecture (Step 1):
        T_norm  ──►  MLP  ──►  Softplus  ──►  (V_max, K_half, n)
                                                       │
                                               HillLayer([S])
                                                       │
                                                    v_pred

    Input : scalar normalized temperature T_norm  (shape: Batch × 1)
    Output: v_pred  (Batch × 1),  plus the three Hill parameters for inspection.

    The final MLP layer feeds into Softplus to guarantee positive parameters.
    n is further offset by +0.5 to keep it physically meaningful (n ≥ 0.5).
    """
    def __init__(self,
                 hidden_dim: int = TrypsinConfig.HIDDEN_DIM,
                 epsilon:    float = TrypsinConfig.EPSILON):
        super().__init__()

        # Parameter-generation MLP: T → raw (V_max, K_half, n)
        self.mlp = nn.Sequential(
            nn.Linear(1, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 3),   # raw outputs for three Hill parameters
        )

        self.hill_layer = HillLayer(epsilon=epsilon)

    def predict_params(self, temperature_norm):
        """
        T_norm → (V_max, K_half, n)   — all strictly positive.

        Softplus ensures positivity; n offset by 0.5 avoids degenerate values
        (n→0 would make the Hill curve a step function, numerically unstable).
        """
        raw    = self.mlp(temperature_norm)            # (Batch, 3)
        V_max  = F.softplus(raw[:, 0:1])
        K_half = F.softplus(raw[:, 1:2])
        n      = F.softplus(raw[:, 2:3]) + 0.5        # n ≥ 0.5
        return V_max, K_half, n

    def forward(self, temperature_norm, substrate_conc):
        """Full forward pass: T_norm + [S]  →  v_pred."""
        V_max, K_half, n = self.predict_params(temperature_norm)
        v_pred = self.hill_layer(V_max, K_half, n, substrate_conc)
        return v_pred, V_max, K_half, n


class TrypsinEnsemble(nn.Module):
    """
    Deep Ensemble of N independent TrypsinKineticsNet members.

    Step 2 — Uncertainty Quantification:
        Each member is trained from a different random initialisation,
        producing diverse predictions.  The variance across members
        quantifies *epistemic* uncertainty — i.e., regions where the
        training data is sparse and the model's knowledge is limited.

        Var(v | T) = (1/N) Σ (v_i - v̄)²

    This variance signal is consumed directly by the MQS strategy in
    active_learning.py to select the most informative next experiment.
    """
    def __init__(self,
                 n_members:  int   = TrypsinConfig.ENSEMBLE_SIZE,
                 hidden_dim: int   = TrypsinConfig.HIDDEN_DIM,
                 epsilon:    float = TrypsinConfig.EPSILON):
        super().__init__()
        self.n_members = n_members
        self.members   = nn.ModuleList([
            TrypsinKineticsNet(hidden_dim=hidden_dim, epsilon=epsilon)
            for _ in range(n_members)
        ])

    def forward(self, temperature_norm, substrate_conc):
        """
        Aggregate predictions from all ensemble members.

        Returns:
            mean_v      : (Batch, 1)  Consensus velocity prediction
            var_v       : (Batch, 1)  Velocity variance  ← epistemic uncertainty
            mean_params : (Batch, 3)  Mean [V_max, K_half, n]
            var_params  : (Batch, 3)  Variance of [V_max, K_half, n]
        """
        all_v, all_params = [], []

        for member in self.members:
            v, V_max, K_half, n = member(temperature_norm, substrate_conc)
            all_v.append(v)
            all_params.append(torch.cat([V_max, K_half, n], dim=-1))

        all_v      = torch.stack(all_v,      dim=0)   # (N, Batch, 1)
        all_params = torch.stack(all_params, dim=0)   # (N, Batch, 3)

        mean_v     = all_v.mean(dim=0)
        var_v      = all_v.var(dim=0)
        mean_params = all_params.mean(dim=0)
        var_params  = all_params.var(dim=0)

        return mean_v, var_v, mean_params, var_params

    def predict_uncertainty(self, temperature_norm, substrate_conc):
        """
        Convenience method: return only the velocity variance.
        Called by the MQS active learning query loop.
        """
        _, var_v, _, _ = self.forward(temperature_norm, substrate_conc)
        return var_v   # (Batch, 1)
